package org.acme

import io.quarkus.arc.DefaultBean
import jakarta.enterprise.context.ApplicationScoped
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedAsyncClient
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient
import java.time.Clock

class Config {

    @ApplicationScoped
    fun clock(): Clock {
        return Clock.systemUTC()
    }

    @DefaultBean
    @ApplicationScoped
    fun enhancedClient(client: DynamoDbAsyncClient, clock: Clock): DynamoDbEnhancedAsyncClient {
        return DynamoDbEnhancedAsyncClient.builder()
                .dynamoDbClient(client)
                .extensions(
                        AutoGeneratedTimestampRecordExtension.builder()
                                .baseClock(clock)
                                .build(),
                        VersionedRecordExtension.builder()
                                .build()
                )
                .build()
    }
}