package org.acme

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey
import java.time.Instant

@DynamoDbBean
data class Greeting(

        @get:DynamoDbPartitionKey
        var id: String,

        @get:DynamoDbAutoGeneratedTimestampAttribute
        var time: Instant? = null
)